### ISSUE TITLE
mvsum() now fails with lme models

### ISSUE THREAD

**Issue by JessicaWeiss** [biostatsPMH/reportRx#17]
I believe the issue is in the new call object definition 
call <- paste(deparse(model$formula), collapse = "") 

Here is an example 
library(nlme)
model <- lme(distance ~ age + Sex, data = Orthodont, random = ~ 1|Subject)
call <- paste(deparse(model$formula), collapse = "") #New
call
call <- paste(deparse(summary(model)$call),collapse="") #Original
call

**Comment by egosv** [comment]
This has been fixed now. Changed to
call <- Reduce(paste, deparse(formula(model$terms), width.cutoff = 500))
which is used for other models.
