### ISSUE TITLE
bugs with puvsum

### ISSUE THREAD

**Issue by ljhklcy** [biostatsPMH/reportRx#19]
It seemed that the puvsum function failed to work while the rm_uvsum function worked. The codes were listed below.
reportRx version 1.0.3
![image](https://github.com/biostatsPMH/reportRx/assets/94365752/6e6ae147-71af-4b28-b89a-79202e890947)

dta is a dataframe, and the response "hnc.number" is 0 or 1 indicating non-hnc or hnc case.

**Comment by lisa-avery** [comment]
reportRx is a deprecated package. It has been replaced by reportRmd, which is optimised for Word documents, but has some pdf functionality. reportRmd is available from CRAN.
