### ISSUE TITLE
covsum

### ISSUE THREAD

**Issue by Avery-Lisa** [biostatsPMH/reportRx#4]
It would be nice to exclude the Full Sample column sometimes

**Comment by egosv** [comment]
This works now quite nicely actually. However, I just found an error thrown in the situation where there in no maincov, i.e. maincov = NULL AND full=FALSE. Although covsum itself exits without error here, both pcovsum and rm_covsum fail. A checking of this situation in covsum should be enough.

**Comment by Avery-Lisa** [comment]
Fixed ... I simply set full=TRUE if maincov =NULL, and updated the
